development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://silffrmbscxicq:7a28ee207002c45cc13175ffbe1cd73d6f5d99a940a1843eb036a01a93e35836@ec2-107-20-193-202.compute-1.amazonaws.com:5432/d9l771fkul1nob
  channel_prefix: app2_production
